### ISSUE TITLE
ats-interoperability-metadata/A.06.IR13.6.spat.rep.md

### ISSUE THREAD

**Issue by AntoRot** [inspire-eu-validation/data#1]
Concerning the codelist attribute, it needs to also consider the xPath of the official ISO repository that is http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_19139_Schemas/resources/codelist/gmxCodelists.xml#MD_SpatialRepresentationTypeCode

**Comment by cportele** [comment]
The current test case does this.
