### ISSUE TITLE
A.3 Encoding

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#17]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Encoding is one of the mandatory elements in "Metadata for interoperability" for datasets and series.
# Proposed Change

There should be at least a test on pure existence for datasets and series if the resource is already in focus of IR 1089/2010.

**Comment by cportele** [comment]
See #25

**Comment by cportele** [comment]
Proposed resolution:
- add test on existence and value range of the metadata element 
- the TG only uses the path distributionInfo/MD_Distribution/distributionFormat, so use this path only in the test

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
