### ISSUE TITLE
A.4 Topological Consistency

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#18]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Not the correctness is tested as written in the purpose, but the existence of a topological consistence metadata element.
# Proposed Change

Correct the purpose.

**Comment by cportele** [comment]
Proposed resolution:
- Implement the proposed change.
- See also #25.

**Comment by cportele** [comment]
Resolution depends on resolution of #27

**Comment by cportele** [comment]
Resolution during [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10) - see #27:
- Implement the proposed change
