### ISSUE TITLE
This ATS clearly needs more work. In general, the ...

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#2]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

This ATS clearly needs more work. In general, the tests are not implementable as they are.
Only IR references are provided. All tests should be against requirements stated in a TG.

**Comment by aquaglia** [comment]
I agree. I hope all requirement numbering is consistent across all Data Spec. TGs

**Comment by cportele** [comment]
References to the TG requirements based on the Data Specification Template have been added.
