### ISSUE TITLE
A.6 Spatial Representation Type

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#22]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The test should be limited to the check if an appropriate value of the codelist has been chosen. A dataset should be considered INSPIRE conformant if such an element is provided.
# Proposed Change

Skip the test on validation of the matching of the given with the advertised representation since this is considered out of scope of conformance testing.

**Comment by cportele** [comment]
See #23.

**Comment by cportele** [comment]
Resolution depends on resolution of #27

**Comment by cportele** [comment]
Resolution during [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10) - see #27:
- Implement the proposed change
