### ISSUE TITLE
A.6 Spatial Representation Type

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#23]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Grab the resource and check the spatial representation. Validate if it matches the advertised representation.
# Proposed Change

Delete this part, is not executable

**Comment by cportele** [comment]
Proposed resolution:
- Implement proposed change

**Comment by cportele** [comment]
Resolution depends on resolution of #27

**Comment by cportele** [comment]
Resolution during [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10) - see #27:
- Implement the proposed change
