### ISSUE TITLE
Open issues

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#24]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

The objective of ATS and testing is to ensure INSPIRE compliant datasets. Therefore, only the requirements should be tested not the recommendations, too. If a recommendation is considered crucial for interoperability it should be upgraded to a requirement. Then you can add a corresponding ATS to this issue.
# Proposed Change

Do not add recommendations to ATS if not really necessary for achieving interoperable datasets.

**Comment by cportele** [comment]
Proposed resolution:
- Remove any recommendations from the test cases.
- MIG to upgrade recommendations that are considered "essential" to requirements in the Technical Guidelines.

**Comment by cportele** [comment]
Added TG change request label as a reminder that the MIG-T should review, if any recommendations should be upgraded.

**Comment by cportele** [comment]
Proposed resolution accepted by default. See [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10#Next-steps).
