### ISSUE TITLE
Open issues

### ISSUE THREAD

**Issue by jensscheerlinck** [inspire-eu-validation/data#25]
_This issue has been extracted from the issue list on:https://ies-svn.jrc.ec.europa.eu/issues/2685_
# Comment

Testing should only cover a test if the required metadata elements are correctly provided. This can be done automatically. Further test methods aiming the feasibility of the thematic content seem to be too advanced.
# Proposed Change

Keep the testing cases on the level of correctly given elements.

**Comment by cportele** [comment]
Proposed resolution:
- Update based on the proposed change.

Alternatively, the test case classification could be changed to "manual".

**Comment by cportele** [comment]
Resolution depends on resolution of #27

**Comment by cportele** [comment]
Resolution during [call on April 28](https://ies-svn.jrc.ec.europa.eu/projects/validation-and-conformity-testing/wiki/MIWP-5_meeting_10) - see #27:
- Implement the proposed change
